### ISSUE TITLE
1 Show chairs

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#1]
## Value proposition

**As a** user,
**I want to** see different kinds of chairs
**so that** I have an overview

## Description

<img src=https://user-images.githubusercontent.com/104770865/175318175-e451e84e-ebcb-438c-ab66-94d0c940caf5.png width=250px>

## Acceptance criteria

- [x] The header is on top and not fixed
- [x] different cards with chair name, description and image are displayed
- [x] The page is vertically scrollable 

## Complexity

Medium 

## Tasks

- [x]  create new branch show-chairs
- [x] create a json with chair data
- [x] create a Card component
- [x] create Card.spec
- [ ] create Card.stories
- [x] display data in Cards
- [x] add style

**Comment by PReichetanz** [comment]
Hello Anna,
a really nice start!

Questions / ideas which came to my mind:
- acceptance criteria "displaying a header withe the App name": You don't need this because it is part of the scribble, but anyways: Is "Find your perfect CHAIR" the name of your app?
- How does the scrolling works and what happens with your heading while scrolling down?
- typo: "...so that **I** have an overview."
