### ISSUE TITLE
5 Filter Styles

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#10]
## Value proposition

**As a** user, 
**I want to** I want to see all scandi / contemporary/ industrial/ mid-century chairs 
**so that** I can see the different chair styles

## Description

<img src=https://user-images.githubusercontent.com/104770865/177100866-6ccd4bee-6695-4912-831a-321870ac162b.png width=320px>

## Acceptance criteria

- [x] There is a home page
- [x] home page displays 4 styles
- [x] each style should lead to the propper chairs

## Complexity

Medium 

## Tasks

- [x] Create branch filter-styles
- [x] Create filter-styles Component
- [x] Create filter-styles.spec
- [x] Add style
