### ISSUE TITLE
6 Like-button

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#15]
## Value proposition

**As a** user,
**I want to** give likes to different chairs
**so that** I can see which chairs I prefer

## Description

<img src=https://user-images.githubusercontent.com/104770865/178226665-e1117c1f-86a8-4534-8eb9-7757f06bf0f1.png width=320px>

## Acceptance criteria

- [x] Every chair has a heart as a button 
- [x] The color of the heart will change when user click the heart
- [x] The hear button can be toggled 

## Complexity

Small 

## Tasks

- [x] Create branch like-button
- [x] Create component LikeButton
- [x] add style to component
