### ISSUE TITLE
7 like-page

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#16]
## Value proposition

**As a** user,
**I want to** see all liked chairs on one site
**so that** have an overview about all liked chairs 

## Description

<img src=https://user-images.githubusercontent.com/104770865/178247884-03969dea-8d77-4ec5-9613-d5a78489ade5.png width=320px>

## Acceptance criteria

- [x] The main page has a navigation which leads the user to the liked chairs
- [x] The page has also a back button that leads the user to the main page

## Complexity

 Medium 

## Tasks

- [x] Create branch like-page
- [x] Create a component Navigation
- [x] Create a navigation on the main page 
- [x] create a path to new page where likes are saved
