### ISSUE TITLE
8 Local Storage

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#17]
## Value proposition

**As a** user,
**I want to** save my liked chairs on my device 
**so that** I have access to them any time

## Acceptance criteria

- [x] the data will be saved and still be shown after closing and reopening the app

## Complexity

 Medium 

## Tasks

- [x] Create branch local-storage
- [x] add local storage
