### ISSUE TITLE
Toggle chair description 

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#2]
## Value proposition

**As a** user,
**I want to** click the description button 
**so that** I can decide either the description text is displayed or hide

## Description

<img src=https://user-images.githubusercontent.com/104770865/175277166-30ab9db9-c4bc-440b-9088-5148592f9cf6.png width=300) />

## Acceptance criteria

- [ ] The cards have a button named description 
- [ ] Tapping on the description button toggles the description text 
- [ ] The size of the Card changes depending if the description text is hide or shown
- [ ] The Cards under the selected Card slide evenly, so that the distance is always the same

## Complexity

Small 

## Tasks

- [ ] Create branch button-description
- [ ] Add logic to the button
- [ ] Create a Button Component 
- [ ] Create Button.spec
- [ ] Create Button.stories
- [ ] Add style

**Comment by mbosselmann** [comment]
Hi Anna,
I like your user story! 💪 I only have one remark:
- your wireframes are really small and I needed to zoom to read the whole text. Maybe you can add larger wireframes for a better reading experience of your user story? 😅
