### ISSUE TITLE
9 Splash screen 

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#21]
## Value proposition

**As a** user,
**I want to** have a start screen 
**so that** I can see the purpose of the app

## Description

<img src=https://user-images.githubusercontent.com/104770865/179480835-c68b3970-6753-4653-8ecd-9e92653aeac4.png width=320px>

## Acceptance criteria

- [x] show splash screen when the user opens the app
- [x] insert Logo on splash screen
- [x] a small description about the app
- [x] a "get started" button that navigates to the main page

## Complexity

Medium 

## Tasks

- [x] Create branch splash-screen
- [x] Create a splash-screen component 
- [x] add logo

**Comment by chris-yooo** [comment]
looks good :) to me

maybe for tasks
[] create the small description about the app
[] dont forget accesabillity -> button
