### ISSUE TITLE
10 design concept

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#22]
## Value proposition

**As a** user,
**I want to** have a nicely designed  and accessible App
**so that**I'm being able to use the app intuitively

## Description

/

## Acceptance criteria

- [x] the app should be accessible and easy to use
- [x] improved UX

## Complexity

Medium 

## Tasks

- [x] Create branch styling
- [x] headers should have the same font-size
- [x] improved accessibility 
- [x] add small logo on every page
