### ISSUE TITLE
3 designer-link

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#3]
## Value proposition

**As a** user,
**I want to** click on the designer name
**so that** I can read more on Wikipedia about the designer

## Description

<img src=https://user-images.githubusercontent.com/104770865/175485609-284c9a90-f443-4c33-b0dd-86fbbaaa4fa2.png width=320px>

## Acceptance criteria

- [ ] The designer name is a Link
- [ ] the designer name is not underlined but highlighted by color

## Complexity

Small 

## Tasks

- [ ] Create branch `designer-link`
- [ ] The designer should be linked to the proper Wikipedia site
- [ ] Add styling to the Link
