### ISSUE TITLE
4 inspiration-img

### ISSUE THREAD

**Issue by AnnaGrasm** [AnnaGrasm/capstone-project#7]
## Value proposition

**As a** user,
**I want to** to see inspiration Images for each chair
**so that** I have an idea how the chairs can bei arranged

## Description

<img src=https://user-images.githubusercontent.com/104770865/176642543-88536f96-b96b-4003-8f35-2eb9899fce1b.png width=320px>

## Acceptance criteria

- [x] images are displayed in a row and have a gap in between
- [x] each child has always 3 inspiration images
- [x] the images are horizontally scrollable  

## Complexity

 Medium 

## Tasks

- [x] Create branch inspiration-img
- [x] Create inspiration-img Component 
- [x] Create inspiration-img.spec
- [x] Create  nspiration-img.stories
- [x]  Add style
